---
name: Code Quality Checks

on:
  push:
    branches: [main, development]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install poetry
        run: pip install poetry
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Check style with flake8 & pylint
        run: |
          poetry run flake8 deepa2/ tests/
          poetry run pylint deepa2/
      - name: Check format with black
        run: poetry run black --check deepa2/ tests/
      - name: Check type hinting with mypy
        run: poetry run mypy deepa2/