---
name: Code Quality Checks

on:
  push:
    branches: [main, development]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry update
      - name: Check style with flake8 & pylint
        run: |
          poetry run flake8 deepa2datasets/ tests/
          poetry run pylint deepa2datasets/
      - name: Check format with black
        run: poetry run black --check .
